=== valtido/ason-js/examples/profile/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "properties": {
    "name": {
      "first": {"type": "string"},
      "last": {"type": "string"}
    },
    "location": {"type": "string"},
    "dob": {"type": "string"},
    "likes": {"type": "number"},
    "image": {"type": "string"}
  },
  "required": ["name","location"]
}

=== valtido/ason-js/public/examples/profile/data2.json
[
  {
    "name": {"first": "Joe", "last":"Doe"},
    "location": "London",
    "dob": "31/06/1988",
    "likes": 0,
    "image":"http://placehold.it/90x90?2"
  },
  {
    "name": {"first": "John", "last": "Smith"},
    "location": "Paris",
    "dob": "31/06/1988",
    "likes": 5,
    "image":"http://placehold.it/90x90?3"
  }
]

=== valtido/ason-js/examples/profile/data.json
[
  {
    "name": {"first": "Valtid", "last": "Caushi", "middle":"Xhemil"},
    "location": "London",
    "dob": "31/06/1988",
    "likes": 0,
    "image":"http://hhhhold.com/90x90?2"
  },
  {
    "name": {"first": "Thomas", "last": "McKiernan"},
    "location": "Paris",
    "dob": "31/06/1988",
    "likes": 5,
    "image":"http://hhhhold.com/90x90?3"
  },
  {
    "name": {"first": "Mario", "last": "Contessa"},
    "location": "Rome",
    "dob": "31/06/1988",
    "likes": 2,
    "image":"http://hhhhold.com/90x90?4"
  }
]

=== valtido/ason-js/public/examples/profile/data.json
[
  {
    "name": {"first": "Valtid", "last": "Caushi", "middle":"Xhemil"},
    "location": "London",
    "dob": "31/06/1988",
    "likes": 0,
    "image":"http://placehold.it/90x90?2"
  },
  {
    "name": {"first": "Thomas", "last": "McKiernan"},
    "location": "Paris",
    "dob": "31/06/1988",
    "likes": 5,
    "image":"http://placehold.it/90x90?3"
  },
  {
    "name": {"first": "Mario", "last": "Contessa"},
    "location": "Rome",
    "dob": "31/06/1988",
    "likes": 2,
    "image":"http://placehold.it/90x90?4"
  },
  {
    "name": {"first": "Gopi","middle":"", "last": "Selva"},
    "location": "Mumbai",
    "dob": "31/06/1908",
    "likes": -11,
    "image":"http://placehold.it/90x90?4"
  }
]
